

services:
  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    environment:
      - AI_SERVICE_URL=http://ai-service:8001
    depends_on:
      - ai-service
    networks:
      - app-network

  ai-service:
    build:
      context: ./ai-service
    container_name: ai-service
    ports:
      - "8001:8001"
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8001
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app-network

  drafts-service:
    build:
      context: ./drafts-service
    container_name: drafts-service
    ports:
      - "8002:8002"
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8002
    networks:
      - app-network

  style-db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=style123
      - POSTGRES_DB=style-db
    ports:
      - "5543:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  user-style-service:
    build: ./user-style-service
    command: ["./wait-for-db.sh"]    
    ports:
      - "8010:8010"
    depends_on:
      - style-db
    networks:
      - app-network
  frontend:
    build:
      context: "./frontend service"
    container_name: frontend
    ports:
      - "5173:80"
    depends_on:
      - api-gateway
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: