version: "3.8"

services:
  ai-service:
    build:
      context: ./ai-service
    container_name: ai-service
    ports:
      - "8001:8001"
    env_file:
      - AI-service/.env
    command: uvicorn fast_api_main:app --host 0.0.0.0 --port 8001
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app-network

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    environment:
      - AI_SERVICE_URL=http://ai-service:8001
    depends_on:
      - ai-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
